### ISSUE TITLE
Request: Performance via multithreading?

### ISSUE THREAD

**Issue by jenhek** [irino/softflowd#11]
Hi,

I am using now for about a year softflowd and I am pretty happy with it.

However, our high-perfermance routers (which are not able anymore to produce netflows)
also generate such high packet rates that softflowd does not catch up anymore.
The typical rate is around 1.5 mps (mega packets/s).

So this is a request for engineering a more performat version of softflowd:

a way could be to distribute the counting over several threads, dispatched via a modulo
operation on the last bits ot the source and destination IPs.

Would something like that be possible?

Best regards, Jens

**Comment by irino** [comment]
Hi,
Sorry for very late response.

I don't recommend multi-threading for softflowd, because this software store flow-data into in-memory binary-tree. It will make many mutex_lock/unlock, if softflowd will be implemented with pthread.

I recently implemented loadbalancing functionality, sending PSAMP functionality and receiving PSAMP functionality.

you can run multiple softflowd processes, such as:

For capture and sending PSAMP to localhost with loadbalancing:
 ./softflowd -l -v psamp -n 127.0.0.1:4739,127.0.0.1:4740 

For receiving PSAMP and converting to Netflow v5:
 ./softflowd -d -R 4739 -v 5 -n <destination-ip>:4739
 ./softflowd -d -R 4740 -v 5 -n <destination-ip>:4739

Please try.
